# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bget < Formula
  desc ""
  homepage ""
  version "1.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/egoist/bget/releases/download/v1.0.5/bget_1.0.5_Darwin_x86_64.tar.gz"
      sha256 "43ff5c45f47aa148a3cfb987ad411e00e3368b11e06145ed98f2daf425001099"

      def install
        bin.install "bget"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/egoist/bget/releases/download/v1.0.5/bget_1.0.5_Darwin_arm64.tar.gz"
      sha256 "3e516795de1ccd0986d113d2a16824c6bac13aa38f3e0254a81272db2c9aa1fb"

      def install
        bin.install "bget"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/egoist/bget/releases/download/v1.0.5/bget_1.0.5_Linux_arm64.tar.gz"
      sha256 "058873e3287aa1d54dd31aea2839a8ce973678c919f225aad1bdd97d270be096"

      def install
        bin.install "bget"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/egoist/bget/releases/download/v1.0.5/bget_1.0.5_Linux_x86_64.tar.gz"
      sha256 "724e3e41ae624fc945c8fad8acdaa8d13db4033ddd7f415a4f92db226f0fef50"

      def install
        bin.install "bget"
      end
    end
  end
end
